global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['173.20.0.6:9090']