global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'congratulationsServer'

    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['host.docker.internal:8098']
  - job_name: 'bridgeServer'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['host.docker.internal:8099']
  - job_name: 'cAdvisor'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']


