INSERT INTO users(id, date, username) VALUES (1, '2022-01-01', 'john_doe');
INSERT INTO users(id, date, username) VALUES (2, '2022-02-01', 'jane_smith');
INSERT INTO users(id, date, username) VALUES (3, '2022-03-01', 'jack_wilson');
INSERT INTO users(id, date, username) VALUES (4, '2022-04-01', 'emily_nguyen');
INSERT INTO users(id, date, username) VALUES (5, '2022-05-01', 'adam_klein');
INSERT INTO users(id, date, username) VALUES (6, '2022-06-01', 'sarah_johnson');
INSERT INTO users(id, date, username) VALUES (7, '2022-07-01', 'kate_garcia');
INSERT INTO users(id, date, username) VALUES (8, '2022-08-01', 'michael_jackson');
INSERT INTO users(id, date, username) VALUES (9, '2022-09-01', 'lisa_kim');
INSERT INTO users(id, date, username) VALUES (10, '2022-10-01', 'tom_wilson');
INSERT INTO users(id, date, username) VALUES (11, '2022-11-01', 'sophie_jones');
INSERT INTO users(id, date, username) VALUES (12, '2022-12-01', 'peter_smith');
INSERT INTO users(id, date, username) VALUES (13, '2023-01-01', 'jason_miller');
INSERT INTO users(id, date, username) VALUES (14, '2023-02-01', 'kelly_nguyen');
INSERT INTO users(id, date, username) VALUES (15, '2023-03-01', 'julia_kim');
INSERT INTO users(id, date, username) VALUES (16, '2023-04-01', 'daniel_lee');
INSERT INTO users(id, date, username) VALUES (17, '2023-05-01', 'lucy_brown');
INSERT INTO users(id, date, username) VALUES (18, '2023-06-01', 'oliver_taylor');
INSERT INTO users(id, date, username) VALUES (19, '2023-07-01', 'carla_diaz');
INSERT INTO users(id, date, username) VALUES (20, '2023-08-01', 'pablo_martinez');

INSERT INTO chats(chat_id, user_id) VALUES (1, 2);
INSERT INTO chats(chat_id, user_id) VALUES (1, 3);
INSERT INTO chats(chat_id, user_id) VALUES (1, 4);
INSERT INTO chats(chat_id, user_id) VALUES (1, 5);
INSERT INTO chats(chat_id, user_id) VALUES (1, 6);
INSERT INTO chats(chat_id, user_id) VALUES (1, 7);
INSERT INTO chats(chat_id, user_id) VALUES (1, 8);
INSERT INTO chats(chat_id, user_id) VALUES (1, 9);
INSERT INTO chats(chat_id, user_id) VALUES (1, 10);
INSERT INTO chats(chat_id, user_id) VALUES (1, 11);
INSERT INTO chats(chat_id, user_id) VALUES (1, 12);
INSERT INTO chats(chat_id, user_id) VALUES (1, 13);
INSERT INTO chats(chat_id, user_id) VALUES (1, 14);
INSERT INTO chats(chat_id, user_id) VALUES (1, 15);
INSERT INTO chats(chat_id, user_id) VALUES (1, 16);
INSERT INTO chats(chat_id, user_id) VALUES (1, 17);
INSERT INTO chats(chat_id, user_id) VALUES (1, 18);
INSERT INTO chats(chat_id, user_id) VALUES (1, 19);
INSERT INTO chats(chat_id, user_id) VALUES (1, 20);
INSERT INTO chats(chat_id, user_id) VALUES (1, 1);