// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: protobuf/bot_to_server_proto/botToServer.proto

package gen_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_bot_to_server_proto_botToServer_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CongratulationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatIDs                []int64 `protobuf:"varint,1,rep,packed,name=chatIDs,proto3" json:"chatIDs,omitempty"`
	UserID                 int64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CongratulationSentence string  `protobuf:"bytes,3,opt,name=congratulationSentence,proto3" json:"congratulationSentence,omitempty"`
}

func (x *CongratulationResponse) Reset() {
	*x = CongratulationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CongratulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CongratulationResponse) ProtoMessage() {}

func (x *CongratulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CongratulationResponse.ProtoReflect.Descriptor instead.
func (*CongratulationResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_bot_to_server_proto_botToServer_proto_rawDescGZIP(), []int{1}
}

func (x *CongratulationResponse) GetChatIDs() []int64 {
	if x != nil {
		return x.ChatIDs
	}
	return nil
}

func (x *CongratulationResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CongratulationResponse) GetCongratulationSentence() string {
	if x != nil {
		return x.CongratulationSentence
	}
	return ""
}

type UserRequest_ChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatID int64 `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
}

func (x *UserRequest_ChatRequest) Reset() {
	*x = UserRequest_ChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest_ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest_ChatRequest) ProtoMessage() {}

func (x *UserRequest_ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest_ChatRequest.ProtoReflect.Descriptor instead.
func (*UserRequest_ChatRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_bot_to_server_proto_botToServer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserRequest_ChatRequest) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

var File_protobuf_bot_to_server_proto_botToServer_proto protoreflect.FileDescriptor

var file_protobuf_bot_to_server_proto_botToServer_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6f, 0x74, 0x5f, 0x74,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x6f, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x25,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x44, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x67, 0x72, 0x61,
	0x74, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x36, 0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x67, 0x72, 0x61, 0x74, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x16, 0x63, 0x6f, 0x6e, 0x67, 0x72, 0x61, 0x74, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x32, 0xc5, 0x01, 0x0a, 0x15, 0x43,
	0x6f, 0x6e, 0x67, 0x72, 0x61, 0x74, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x61, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x43, 0x6f, 0x6e,
	0x67, 0x72, 0x61, 0x74, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x67,
	0x72, 0x61, 0x74, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_bot_to_server_proto_botToServer_proto_rawDescOnce sync.Once
	file_protobuf_bot_to_server_proto_botToServer_proto_rawDescData = file_protobuf_bot_to_server_proto_botToServer_proto_rawDesc
)

func file_protobuf_bot_to_server_proto_botToServer_proto_rawDescGZIP() []byte {
	file_protobuf_bot_to_server_proto_botToServer_proto_rawDescOnce.Do(func() {
		file_protobuf_bot_to_server_proto_botToServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_bot_to_server_proto_botToServer_proto_rawDescData)
	})
	return file_protobuf_bot_to_server_proto_botToServer_proto_rawDescData
}

var file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_bot_to_server_proto_botToServer_proto_goTypes = []interface{}{
	(*UserRequest)(nil),             // 0: bridgeServer_service.UserRequest
	(*CongratulationResponse)(nil),  // 1: bridgeServer_service.CongratulationResponse
	(*UserRequest_ChatRequest)(nil), // 2: bridgeServer_service.UserRequest.ChatRequest
	(*emptypb.Empty)(nil),           // 3: google.protobuf.Empty
}
var file_protobuf_bot_to_server_proto_botToServer_proto_depIdxs = []int32{
	0, // 0: bridgeServer_service.CongratulationService.SaveUserInfo:input_type -> bridgeServer_service.UserRequest
	3, // 1: bridgeServer_service.CongratulationService.GetDataForCongratulations:input_type -> google.protobuf.Empty
	3, // 2: bridgeServer_service.CongratulationService.SaveUserInfo:output_type -> google.protobuf.Empty
	1, // 3: bridgeServer_service.CongratulationService.GetDataForCongratulations:output_type -> bridgeServer_service.CongratulationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_bot_to_server_proto_botToServer_proto_init() }
func file_protobuf_bot_to_server_proto_botToServer_proto_init() {
	if File_protobuf_bot_to_server_proto_botToServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CongratulationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequest_ChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_bot_to_server_proto_botToServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_bot_to_server_proto_botToServer_proto_goTypes,
		DependencyIndexes: file_protobuf_bot_to_server_proto_botToServer_proto_depIdxs,
		MessageInfos:      file_protobuf_bot_to_server_proto_botToServer_proto_msgTypes,
	}.Build()
	File_protobuf_bot_to_server_proto_botToServer_proto = out.File
	file_protobuf_bot_to_server_proto_botToServer_proto_rawDesc = nil
	file_protobuf_bot_to_server_proto_botToServer_proto_goTypes = nil
	file_protobuf_bot_to_server_proto_botToServer_proto_depIdxs = nil
}
